### ISSUE TITLE
argument must be an int, or have a fileno() method.

### ISSUE THREAD

**Issue by obeleh** [DinoTools/pysslscan#21]
Installing is successful

```
sjuul_transceptor_technology@development03:~$ sudo pip install sslscan
The directory '/home/sjuul_transceptor_technology/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sud
o, you may want sudo's -H flag.
The directory '/home/sjuul_transceptor_technology/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sud
o, you may want sudo's -H flag.
Collecting sslscan
  Downloading sslscan-0.5.tar.gz
Collecting flextls>=0.3 (from sslscan)
  Downloading flextls-0.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from sslscan)
Building wheels for collected packages: sslscan, flextls
  Running setup.py bdist_wheel for sslscan
  Stored in directory: /home/sjuul_transceptor_technology/.cache/pip/wheels/a2/7d/e6/7fab11a08a32575bdf490d391f2c43513211d0b818d3c5fa37
  Running setup.py bdist_wheel for flextls
  Stored in directory: /home/sjuul_transceptor_technology/.cache/pip/wheels/d1/44/4b/696c58b1347c8bf13b2b4283da24c7509dd6f263f3a35c2e1b
Successfully built sslscan flextls
Installing collected packages: flextls, sslscan
Successfully installed flextls-0.3 sslscan-0.5
```
exception
```
sjuul_transceptor_technology@development03:~$ pysslscan scan --scan=protocol.http --scan=vuln.heartbleed --scan=server.renegotiation   --scan=server.preferred_ciphers --scan=server.ciphers   --report=term:rating=ssllabs.2009e --ssl2 --ssl3 
--tls10 --tls11 --tls12 http://www.google.com
Traceback (most recent call last):
  File "/usr/local/bin/pysslscan", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/sslscan/ui.py", line 560, in run
    sys.exit(func(args))
  File "/usr/local/lib/python2.7/dist-packages/sslscan/ui.py", line 248, in run_scan
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/__init__.py", line 226, in run
    self.run_scans()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/__init__.py", line 247, in run_scans
    module.run()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/module/scan/protocol_http.py", line 22, in run
    server_info = self._get_server_info()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/module/scan/__init__.py", line 732, in _get_server_info
    conn_ssl = self._connect_auto()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/module/scan/__init__.py", line 744, in _connect_auto
    conn_ssl = self._connect_openssl()
  File "/usr/local/lib/python2.7/dist-packages/sslscan/module/scan/__init__.py", line 802, in _connect_openssl
    conn_ssl = SSL.Connection(ctx, conn)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 827, in __init__
    set_result = _lib.SSL_set_fd(self._ssl, _asFileDescriptor(self._socket))
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 208, in _asFileDescriptor
    raise TypeError("argument must be an int, or have a fileno() method.")
TypeError: argument must be an int, or have a fileno() method.
``` 

I get the same result on win8.1 and Ubuntu 14.10 (GNU/Linux 3.16.0-33-generic x86_64)

**Comment by obeleh** [comment]
OpenSSL version

```
sjuul_transceptor_technology@development03:~$ openssl version -v
OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by phibos** [comment]
Thanks for reporting the bug. I could reproduce the error in my test environment and have pushed a fix a few minutes ago. Can you check if the fix in the master branch works for you?

**Comment by obeleh** [comment]
I've pulled from master:

```
C:\Users\sjuul\workspace\pysslscan>pysslscan scan --scan=protocol.http --scan=vuln.heartbleed --scan=server.renegotiation   --scan=server.preferred_ciphers --scan=server.ciphers   --report=term:rating=ssllabs.2009e --ssl2 --ssl3 http://www.google.com
Traceback (most recent call last):
  File "C:\Python27\Scripts\pysslscan-script.py", line 9, in <module>
    load_entry_point('sslscan==0.5', 'console_scripts', 'pysslscan')()
  File "C:\Python27\lib\site-packages\sslscan-0.5-py2.7.egg\sslscan\ui.py", line 560, in run
    sys.exit(func(args))
  File "C:\Python27\lib\site-packages\sslscan-0.5-py2.7.egg\sslscan\ui.py", line 248, in run_scan
    scanner.run()
  File "C:\Python27\lib\site-packages\sslscan-0.5-py2.7.egg\sslscan\__init__.py", line 226, in run
    self.run_scans()
  File "C:\Python27\lib\site-packages\sslscan-0.5-py2.7.egg\sslscan\__init__.py", line 247, in run_scans
    module.run()
  File "C:\Python27\lib\site-packages\sslscan-0.5-py2.7.egg\sslscan\module\scan\server_renegotiation.py", line 41, in run
    conn_ssl = SSL.Connection(ctx, conn)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 827, in __init__
    set_result = _lib.SSL_set_fd(self._ssl, _asFileDescriptor(self._socket))
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 208, in _asFileDescriptor
    raise TypeError("argument must be an int, or have a fileno() method.")
TypeError: argument must be an int, or have a fileno() method.
```

I've checked whether I have the commit you mention (bde442c). I'm up to date.

**Comment by phibos** [comment]
Thanks for testing.

It's the same problem as the error before but in an other scan module. I have fixed the error. Can you check if it works for you now.

**Comment by obeleh** [comment]
```
www.google.com
==============

Supported Server Cipher(s):
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_ECDHE_RSA_WITH_RC4_128_
SHA←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_ECDHE_RSA_WITH_AES_128_
CBC_SHA←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_RSA_WITH_RC4_128_SHA←[0
m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_RSA_WITH_RC4_128_MD5←[0
m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_RSA_WITH_AES_128_CBC_SH
A←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;32m 256 bits←[0m ←[0mTLS_ECDHE_RSA_WITH_AES_256_
CBC_SHA←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;32m 256 bits←[0m ←[0mTLS_RSA_WITH_AES_256_CBC_SH
A←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 168 bits←[0m ←[0mTLS_ECDHE_RSA_WITH_3DES_EDE
_CBC_SHA←[0m
  Accepted  ←[0mSSLv3  ←[0m ←[0;33m 168 bits←[0m ←[0mTLS_RSA_WITH_3DES_EDE_CBC_S
HA←[0m

Preferred Server Cipher(s):
  ←[0mSSLv3  ←[0m ←[0;33m 128 bits←[0m ←[0mTLS_ECDHE_RSA_WITH_RC4_128_SHA←[0m

Session:
  Compression: ←[0mnone←[0m

TLS renegotiation:
  Supported: ←[0myes←[0m
  Secure: ←[0;32myes←[0m

HTTP Information
  Server: ←[0m GFE/2.0←[0m
  Strict-Transport-Security: ←[0mno←[0m
  Status-Code: ←[0m302←[0m
  Status-Message: ←[0mFound←[0m
  Version: ←[0mHTTP/1.1←[0m

Heartbleed(Vulnerability)
  Heartbeat Extension present: ←[0mno←[0m
  Vulnerable: ←[0mno←[0m
```

It looks like it works. What's with the weird characters?

**Comment by phibos** [comment]
The wired characters are escape sequences for *nix shells (bash, zsh, ...) to change the color and font of the text. Are you using windows?

You can disabled colored output by using "--report=term:rating=none"

**Comment by obeleh** [comment]
Ah ok ty :)

**Comment by phibos** [comment]
I have created a new issue #22 to hopefully support highlighting also on windows in the next release.
